---
title: "Claessen Project"
output: 
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: true
    theme: cosmo
    df_print: paged
    highlight: tango
    # code_folding: hide
---

<script>
$(document).ready(function() {
  $items = $('div#TOC li');
  $items.each(function(idx) {
    num_ul = $(this).parentsUntil('#TOC').length;
    $(this).css({'text-indent': num_ul * 10, 'padding-left': 0});
  });

});
</script>

# Load libraries

```{r}
library(bvpSolve)
library(ggplot2)
library(plyr)
library(gplots)
options(scipen = 999)
```

```{r}

#####################
# DmDlSolver (Algorithm 1 in the O2 pathway paper)
# input: pao2, pvo2, q, hb, pA, pmito
# output: dmo2, dlo2
#####################

model <- function(x,y,parms) {
  q <- parms$q
  hb <- parms$hb
  pA <- parms$pA
  pmito <- parms$pmito
  # model represented as a list
  return(list( c(
    (y[3]/(TT*q*o2ct(y[1],hb,1)))*(pA-y[1]), # y[1] = Lung o2 
    -(y[4]/(TT*q*o2ct(y[2],hb,1)))*(y[2]-pmito), #y [2] = Muscle o2
    0, # y[3] = dlo2
    0  # y[4] = dmo2
  )))
}

boundCond <- function(i,y,parms) { 
  pvo2 <- parms$pvo2
  pao2 <- parms$pao2 
  # boundary conditions
  if (i==1) return(y[1]-pvo2) # y[1] = pvo2, at t=0 
  if (i==2) return(y[2]-pao2) # y[2] = pao2, at t=0 
  if (i==3) return(y[1]-pao2) # y[1] = pao2, at t=T 
  if (i==4) return(y[2]-pvo2) # y[2] = pvo2, at t=T 
}

DmDlSolver <- function(...,pao2,pvo2,q,hb,pA,pmito,
                       init_dmo2=1, init_dlo2=1,
                       stepsize=0.01, errtol=1e-3, NITER=10000) {
  
  # error checking
  if (pao2>pA) {
    cat("Impossible measurements: pao2 > pA\n")
    return(data.frame(dmo2=NA,dlo2=NA,pmcap=NA))
  }
  if (pmito>pvo2) {
    cat("Impossible parameters: pmito > pvo2; setting pmito to pvo2-0.05\n")
    pmito <- pvo2-0.05
  }
  
  # initial values  
  xguess = seq(0, TT, by = stepsize)
  yguess = matrix(nrow = 4, ncol = length(xguess), data = 0)
  rownames(yguess) <- c("LungO2", "MuscleO2","dlo2","dmo2")
  yguess[1,] <- (pvo2+(pao2-pvo2)*xguess/TT) # initialize the venous blood gas in the lung
  yguess[2,] <- (pao2-(pao2-pvo2)*xguess/TT) # initialize the arterial blood gas in the muscle
  yguess[3,] <- init_dlo2
  yguess[4,] <- init_dmo2
  
  # solver call
  parms <- list(pao2 = pao2,pvo2 = pvo2,q=q,hb=hb,pA=pA,pmito=pmito)
  Sol <- bvptwp(func = model, 
                bound = boundCond, 
                x = seq(0, TT, by = stepsize), 
                ynames = c("L(x)","M(x)","dlo2","dmo2"),
                parms=parms,
                leftbc=2,
                xguess=xguess,
                yguess=yguess,
                verbose=FALSE,
                atol=errtol,
                nmax=10000)
  
  dmo2 <- Sol[1,"dmo2"]
  dlo2 <- Sol[1,"dlo2"]
  pmcap <- sintegral(Sol[,1],Sol[,"M(x)"])$int / TT # mean value of pmcap(x), computed by integration
  dmdlpcap <- data.frame(dmo2=dmo2,dlo2=dlo2,pmcap=pmcap)
  rownames(dmdlpcap) <- NULL
  return(dmdlpcap)
}

#####################
# bgSolver: blood gas solver, with mitochondrial circuit (Algorithm 2 in the O2 pathway paper)
# input: all the parameters that define the physiology = dmo2, dlo2, q, va, hb, p50, vmax
# output: blood gases = pao2, pvo2, and therefore vo2
#####################

model.bg <- function(x,y,parms) {
  q <- parms$q
  hb <- parms$hb
  dmo2 <- parms$dmo2
  dlo2 <- parms$dlo2
  va <- parms$va
  return(list( c(
    (dlo2/(TT*q*odc(y[1],hb,1)))*((PIO2-(q*(odc(y[5],hb,0)-odc(y[4],hb,0)))/(va*K))-y[1]), # y[1] = Lung o2; rather than use an auxiliary variable for pA I have replaced it with its calculated value
    -(dmo2/(TT*q*odc(y[2],hb,1)))*(y[2]-y[3]), # y[2] = Muscle o2
    0, # y[3] = pmito
    0, # y[4] = pvo2 
    0  # y[5] = pao2 
  )))
}

bound.bg <- function(i,y,parms) { 
  q <- parms$q
  hb<- parms$hb
  va <- parms$va
  p50 <- parms$p50
  vmax <- parms$vmax
  if (i==1) return(y[3]-(p50/(-1+(vmax/(q*(odc(y[5],hb,0)-odc(y[4],hb,0))))))) # pmito formula; y[3] = pmito
  if (i==2) return(y[1]-y[4]) # at t=0, y[1] = y[4], the unknown constant for pvo2
  if (i==3) return(y[2]-y[5]) # at t=0, y[2] = y[5], the unknown constant for pao2
  if (i==4) return(y[1]-y[5]) # at t=T, y[1] = pao2 ie y[5]
  if (i==5) return(y[2]-y[4]) # at t=T, y[2] = pvo2 ie y[4]
}

bgSolver <- function(...,va,q,hb,dmo2,dlo2,p50,vmax,
                     pao2_init=120,pvo2_init=15,pmito_init=5,
                     stepsize=0.01,errtol=1e-3,NITER=10000) {
  
  # initial values
  xguess = seq(0,TT,by=stepsize)
  yguess = matrix(nrow = 5, ncol = length(xguess), data = 0)
  rownames(yguess) <- c("L(x)", "M(x)","pmito","pvo2","pao2")
  yguess[1,] <- (pvo2_init+(pao2_init-pvo2_init)*xguess/TT) # initialize the venous blood gas in the lung
  yguess[2,] <- (pao2_init-(pao2_init-pvo2_init)*xguess/TT) # initialize the arterial blood gas in the muscle
  yguess[3,] <- pmito_init
  yguess[4,] <- pvo2_init
  yguess[5,] <- pao2_init
  
  # solver call
  parms <- list(dmo2 = dmo2,dlo2 = dlo2,va=va,q=q,hb=hb,p50=p50,vmax=vmax)
  
  Sol <- bvptwp(func = model.bg, bound=bound.bg, x = seq(0, TT, by = stepsize), ynames = c("L(x)", "M(x)","pmito","pvo2","pao2"),parms=parms,atol=errtol,leftbc=3,xguess=xguess,yguess=yguess,verbose=FALSE,nmax=NITER)
  
  # solution quantities of interest
  pao2 <- Sol[1,3]
  pvo2 <- Sol[1,2] 
  pmito <- Sol[1,4]
  avo2 <- (odc(pao2,hb,0)-odc(pvo2,hb,0))/10
  vo2 <- q*avo2*10
  pA <- PIO2 - vo2/(va*K)
  bg <- data.frame(pao2=pao2,pvo2=pvo2,avo2=avo2,vo2=vo2,pA=pA,pmito=pmito,vmax=vmax,q=q)
  rownames(bg) <- NULL
  return(bg)
}


###############
# O2 dissociation curve and its derivative
# Dash-Bassingthwaighte formulation used here, but Kelman is another popular alternative
###############

odc <- function(x,hb,flag) { #wrapper for odcDB
  if (flag==0) return((0.003*x+1.39*hb*odcDB(x,hb,flag))*10) # o2 content: mL O2/ L blood
  if (flag==1) return(odcDB(x,hb,flag)*hb*1.39*10+0.03) # o2 content DERIVATIVE, ie change in o2 content per delta pao2
}


# Simulation of oxyhemoglobin (HbO2) and carbomino hemoglobin (HbCO2)
# dissociation curves and computation of total O2 and CO2 contents in 
# the whole blood (Dash-Bassingthwaighte, ABME 38(4):1683-1701, 2010)

odcDB <- function(pO2,hb,flag) {
    
# set pCO2, pH, DPG, Temp to default values unless explicitly modeled
    pCO2 <- 40
    pH <- 7.24
    DPG <- 0.00465
    Temp <- 37
    Hct <- hb
    
    # Parameters those are fixed in the model (i.e., water fractions, hemoglobin
    # concentration in RBCs, equilibrium constants, and Hill coefficient)
    Wpl = 0.94             # fractional water space in plasma unitless
    Wrbc = 0.65            # fractional water space in RBCs unitless
    Rrbc = 0.69            # Gibbs-Donnan ratio across RBC membrane unitless
    Hbrbc = 5.18e-3        # hemoglobin concentration in RBCs M
    K2 = 2.95e-5           # CO2 + HbNH2 equilibrium constant unitless
    K2dp = 1.0e-6          # HbNHCOOH dissociation constant M
    K2p = K2/K2dp          # kf2p/kb2p 1/M
    K3 = 2.51e-5           # CO2 + O2HbNH2 equilibrium constant unitless
    K3dp = 1.0e-6          # O2HbNHCOOH dissociation constant M
    K3p = K3/K3dp          # kf3p/kb3p 1/M
    K5dp = 2.63e-8         # HbNH3+ dissociation constant M
    K6dp = 1.91e-8         # O2HbNH3+ dissociation constant M
    nhill = 2.7            # Hill coefficient unitless
    n0 = nhill-1.0         # deviation of Hill coefficient or cooperativity from
    # the stochiometry of O2 for each heme site
    
    # Variables those are privately fixed in the model with the standard 
    # physiological values (i.e., pH0, pCO20, DPG0, Temp0)
    pO20 = 100.0           # standard O2 partial pressure in blood mmHg
    pCO20 = 40.0           # standard CO2 partial pressure in blood mmHg
    pH0 = 7.24             # standard pH in RBCs unitless
    DPG0 = 4.65e-3         # standard 23-DPG concentration in RBCs M
    Temp0 = 37.0           # standard temperature in blood degC
    fact = 1.0e-6/Wpl      # a multiplicative factor M/mmHg
    alphaO20 = fact*1.37	# solubility of O2 in water at 37 C M/mmHg
    alphaCO20 = fact*30.7	# solubility of CO2 in water at 37 C M/mmHg
    O20 = alphaO20*pO20	# standard O2 concentration in RBCs M
    CO20 = alphaCO20*pCO20	# standard CO2 concentration in RBCs M
    Hp0 = 10^(-pH0)        # standard H+ concentration in RBCs M
    pHpl0 = pH0-log10(Rrbc)	# standard pH in plasma unitless
    P500 = 26.8            # standard pO2 at 50# SHbO2 mmHg
    C500 = alphaO20*P500	# standard O2 concentration at 50# SHbO2 M
    
    # Calculation of intermediate variables and the indices n1, n2, n3, and 
    # n4 in the computations of SHbO2 & SHbCO2
    Wbl = (1-Hct)*Wpl + Hct*Wrbc
    pHpl = pH-log10(Rrbc)
    pHpldiff = pHpl-pHpl0
    pHdiff = pH-pH0
    pCO2diff = pCO2-pCO20
    DPGdiff = DPG-DPG0
    Tempdiff = Temp-Temp0
    alphaO2 = fact*(1.37 - 0.0137*Tempdiff + 0.00058*Tempdiff^2)
    alphaCO2 = fact*(30.7 - 0.57*Tempdiff + 0.02*Tempdiff^2)
    pK1 = 6.091 - 0.0434*pHpldiff + 0.0014*Tempdiff*pHpldiff
    K1 = 10^(-pK1)
    O2 = alphaO2*pO2 ##
    CO2 = alphaCO2*pCO2
    Hp = 10^(-pH) ##
    Hppl = 10^(-pHpl)
    
    Term1 = K2p*(1+K2dp/Hp)
    Term2 = K3p*(1+K3dp/Hp)
    Term3 = (1+Hp/K5dp)
    Term4 = (1+Hp/K6dp)
    Term10 = K2p*(1+K2dp/Hp0)
    Term20 = K3p*(1+K3dp/Hp0)
    Term30 = (1+Hp0/K5dp)
    Term40 = (1+Hp0/K6dp)
    Kratio10 = (Term10*CO20+Term30)/(Term20*CO20+Term40)
    Kratio11 = (Term1*CO20+Term3)/(Term2*CO20+Term4)
    Kratio12 = (Term10*alphaCO20*pCO2+Term30)/(Term20*alphaCO20*pCO2+Term40)
    K4dp = Kratio10*O20^n0/C500^nhill
    K4tp = K4dp/O20^n0
    Kratio20 = Kratio10/K4tp
    Kratio21 = Kratio11/K4tp
    Kratio22 = Kratio12/K4tp
    
    P501 = 26.765 - 21.279*pHdiff + 8.872*pHdiff^2
    P502 = 26.80 + 0.0428*pCO2diff + 3.64e-5*pCO2diff^2
    P503 = 26.78 + 795.633533*DPGdiff - 19660.8947*DPGdiff^2
    P504 = 26.75 + 1.4945*Tempdiff + 0.04335*Tempdiff^2 + 0.0007*Tempdiff^3
    C501 = alphaO20*P501
    C502 = alphaO20*P502
    C503 = alphaO20*P503
    C504 = alphaO2*P504
    
    if (abs(pH-pH0) < 1.0e-6) {
        n1 = 1.0       # can be any arbitrary value
    } else {
        n1 = (log10(Kratio21)-nhill*log10(C501))/(pH-pH0)
    }
    if (abs(pCO2-pCO20) < 1.0e-6) {
        n2 = 1.0       # can be any arbitrary value
    } else {
        n2 = (log10(Kratio22)-nhill*log10(C502))/(log10(CO20)-log10(CO2))
    }
    if (abs(DPG-DPG0) < 1.0e-6) {
        n3 = 1.0        # can be any arbitrary value
    } else {
        n3 = (log10(Kratio20)-nhill*log10(C503))/(log10(DPG0)-log10(DPG))
    }
    if (abs(Temp-Temp0) < 1.0e-6) {
        n4 = 1.0       # can be any arbitrary value
    } else {
        n4 = (log10(Kratio20)-nhill*log10(C504))/(log10(Temp0)-log10(Temp))
    }
    Term5 = (Hp0/Hp)^n1*(CO20/CO2)^n2*(DPG0/DPG)^n3*(Temp0/Temp)^n4
    
    # Calculation of Hill coefficients (KHbO2 and KHbCO2) O2 and CO2 saturations
    # of hemoglobin (SHbO2 and SHbCO2) and O2 and CO2 contents in blood. These 
    # are computed as functions of pO2 and pCO2. Also compute the concentrations
    # of all the components of HbO2 and HbCO2.
    K4p = K4dp*(O2/O20)^n0*Term5
    KHbO2 = K4p*(Term2*CO2+Term4)/(Term1*CO2+Term3)
    KHbO2deriv = n0*K4dp*((O2/O20)^(n0-1))*Term5
    KHbCO2 = (Term1+Term2*K4p*O2)/(Term3+Term4*K4p*O2)
    
    ######
    SHbO2 = KHbO2*O2/(1+KHbO2*O2)
    beta = ((KHbO2*(n0+1))/((1+KHbO2*O2)^2))*(alphaO20) # convert back to mmHg from molarity
    ######
    
    SHbCO2 = KHbCO2*CO2/(1+KHbCO2*CO2)
    O2free = Wbl*alphaO2*pO2
    O2bound = 4*Hct*Hbrbc*SHbO2
    O2total = O2free+O2bound
    O2content = 2225.6*O2total
    CO2free = Wbl*alphaCO2*pCO2
    CO2bicarb = ((1-Hct)*Wpl+Hct*Wrbc*Rrbc)*(K1*alphaCO2*pCO2/Hppl)
    CO2bound = 4*Hct*Hbrbc*SHbCO2
    CO2total = CO2free+CO2bicarb+CO2bound
    CO2content = 2225.6*CO2total

    if (flag==1) {
        return(beta)
    } else return(SHbO2)
    
    
    
    ## Some extra variables 
    # 	HbNH2 = Hbrbc/((Term1*CO2+Term3)+ K4p*O2*(Term2*CO2+Term4))
    # 	HbNH3p = HbNH2*Hp/K5dp
    # 	O2HbNH2 = K4p*O2*HbNH2
    # 	O2HbNH3p = O2HbNH2*Hp/K6dp
    # 	HbNHCOOH = K2p*CO2*HbNH2
    # 	HbNHCOOm = K2dp*HbNHCOOH/Hp
    # 	O2HbNHCOOH = K3p*CO2*O2HbNH2
    # 	O2HbNHCOOm = K3dp*O2HbNHCOOH/Hp
    # 	SHbO2kin = (O2HbNH2+O2HbNH3p+O2HbNHCOOH+O2HbNHCOOm)/Hbrbc
    # 	SHbCO2kin = (HbNHCOOH+HbNHCOOm+O2HbNHCOOH+O2HbNHCOOm)/Hbrbc
    # 
    # 	O2freepl1 = Wpl*(1-Hct)*alphaO2*pO2
    # 	O2freepl2 = 2225.6*O2freepl1
    # 	O2freerbc1 = Wrbc*Hct*alphaO2*pO2
    # 	O2freerbc2 = 2225.6*O2freerbc1
    # 	O2boundrbc1 = 4*Hct*Hbrbc*SHbO2
    # 	O2boundrbc2 = 2225.6*O2boundrbc1
    # 	CO2freepl1 = Wpl*(1-Hct)*alphaCO2*pCO2
    # 	CO2freepl2 = 2225.6*CO2freepl1
    # 	CO2freerbc1 = Wrbc*Hct*alphaCO2*pCO2
    # 	CO2freerbc2 = 2225.6*CO2freerbc1
    # 	CO2bicarbpl1 = Wpl*(1-Hct)*K1*alphaCO2*pCO2/Hppl
    # 	CO2bicarbpl2 = 2225.6*CO2bicarbpl1
    # 	CO2bicarbrbc1 = Wrbc*Hct*Rrbc*K1*alphaCO2*pCO2/Hppl
    # 	CO2bicarbrbc2 = 2225.6*CO2bicarbrbc1
    # 	CO2boundrbc1 = 4*Hct*Hbrbc*SHbCO2
    # 	CO2boundrbc2 = 2225.6*CO2boundrbc1
    
    #-----------------------------------------------------------------------------
    # The equations for O2 and CO2 saturations of hemoglobin (SHbO2 and SHbCO2)  
    # are derived by considering the various kinetic reactions involving the
    # binding of O2 and CO2 with hemoglobin in RBCs:
    #
    #            kf1p       K1dp
    # 1. CO2+H2O <--> H2CO3 <--> HCO3- + H+  K1=(kf1p/kb1p)*K1dp
    #            kb1p		K1 = 7.43e-7 M K1dp = 5.5e-4 M
    #
    #              kf2p          K2dp
    # 2. CO2+HbNH2 <--> HbNHCOOH <--> HbNHCOO- + H+  K2=(kf2p/kb2p)*K2dp
    #              kb2p		K2 = 2.95e-5 K2dp = 1.0e-6 M
    #
    #                kf3p            K3dp
    # 3. CO2+O2HbNH2 <--> O2HbNHCOOH <--> O2HbNHCOO- + H+ K3=(kf3p/kb3p)*K3dp
    #                kb3p		K3 = 2.51e-5 K3dp = 1.0e-6 M
    #
    #              kf4p          
    # 4. O2+HbNH2 <--> O2HbNH2  K4p=K4dp*func([O2][H+][CO2][DPG]T)
    #              kb4p		K4dp and K4p are to be determined
    #
    #    func = ([O2]/[O2]s)^n0*([H+]s/[H+])^n1*([CO2]s/[CO2])^n2*
    #           ([DPG]s/[DPG])^n3*(Temps/Temp)^n4
    #
    #           K5dp
    # 5. HbNH3+ <--> HbNH2 + H+  K5 = 2.63e-8 M
    #
    #             K6dp
    # 6. O2HbNH3+ <--> O2HbNH2 + H+  K6 = 1.91e-9 M
    #
    # The association and dissociation rate constants of O2 with hemoglobin is
    # assumed to be dependent on [O2] [H+] [CO2] [DPG] and temperature (Temp)
    # such that the equilibrium constant K4p is proportional to ([O2]/[O2]s)^n0
    # ([H+]s/[H+])^n1 ([CO2]s/[CO2])^n2 ([DPG]s/[DPG])^n3 and (Temps/Temp)^n4.
    # The problem is to estimate the values of the proportionality constant K4dp 
    # and the indices n0 n1 n2 n3 and n4 such that SHbO2 is 50# at pO2 = 26.8 
    # mmHg pH = 7.24 pCO2 = 40 mmHg [DPG] = 4.65 mM and Temp = 37 C in RBCs 
    # and the HbO2 dissociation curve shifts appropriately w.r.t. pH and pCO2.
    #----------------------------------------------------------------------------
} 

```

```{r}
library(tidyverse)
library(Bolstad2)
library(bvpSolve) 


########################
# CONSTANTS
########################
FIO2 <- 0.21
PIO2 <- (760-47)*FIO2 # partial pressure of inspired o2, Torr; pio2 = 149.7 for fio2=0.21
K <- 1.159 # ml o2 / ml air / Torr
TT = 1 # transit time set arbitrarily to 1 as the calculations are invariant to its value, but useful conceptually

# Mitochondrial constants
P50REF <- 0.24 # mmHg
VRESERVE <- 1.8 # VO2 Knee extension / VO2 cycle, Vo2 normalized to lean mass of exercise muscle; sets a lower bound on vmax (ratios derived from data in Esposito et al 2010)

########################
# Input measurements: pao2 (mmHg), pvo2 (mmHg), paco2 (mmHg), hb (g/dL), vo2 (mL/min), vco2 (mL/min)
# Output O2 pathway parameters: va (L/min), q (L/min), dmo2 (mL/mmHg/min), dlo2 (mL/mmHg/min), vmax (L/min)
# Output O2 tensions: pA (mmHg), pmito (mmHg), average pmcap (mmHg)
########################

measurements <- data.frame(pao2=97, paco2 = 40, pvo2=21, hb=14, vo2=1600, vco2=1900) # sample values for a single individual

data_params <- 
    mutate(measurements,
           o2ct.art = mapply(odc,x=pao2,hb=hb,flag=0)/10, # mL O2/ dL blood
           o2ct.ven = mapply(odc,x=pvo2,hb=hb,flag=0)/10, # mL O2/ dL blood
           va=vco2/(K*paco2), # L/min (BTPS), vco2 in mL/min (STPD)
           avo2 = o2ct.art - o2ct.ven, # mL/dL
           q = 0.1*vo2/avo2, # L/min
           o2deliv = q*o2ct.art*10/1000, # L O2/min
           pA = PIO2-vo2/(va*K), # mmHg; vo2 here in mL O2/min (STPD)
           vmax = VRESERVE*vo2, # mL O2/min
           p50 = P50REF, # mmHg
           pmito = p50/((vmax/vo2) - 1)) #mmHg 

dmdlpcap <- do.call(DmDlSolver,data_params)

o2params <- select(data_params,va,q,hb,p50,vmax) %>% mutate(dmo2=dmdlpcap$dmo2,dlo2=dmdlpcap$dlo2)

bg <- do.call(bgSolver,o2params)
```

