---
title: "R Notebook"
output: html_notebook
---
data from https://rawgit.com/bioinformatics-core-shared-training/microarray-analysis/master/affymetrix.nb.html

```{r}
library(affy)
targetsFile <- "phenodata.txt"
pd <- read.AnnotatedDataFrame(targetsFile,header=TRUE,sep="",row.names=1)
pData(pd)

```

```{r}
raw <-ReadAffy(celfile.path = ".", filenames=rownames(pData(pd)),phenoData = pd)
boxplot(raw,col="red",las=2)
hist(log2(pm(raw[,1])),breaks=100,col="steelblue",main="PM",xlim=c(4,14))

```

```{r}
mva.pairs(pm(raw)[,1:3],plot.method="smoothScatter")
mva.pairs(pm(raw)[,4:6],plot.method="smoothScatter")

```

```{r}
library(affyPLM)
plmset <- fitPLM(raw)
NUSE(plmset,las=2)
RLE(plmset,las=2)

```


```{r}
par(mfrow=c(2,3))
image(raw[,1])
image(raw[,2])
image(raw[,3])
image(raw[,4])
image(raw[,5])
image(raw[,6])

```
```{r}
eset <- rma(raw)
boxplot(exprs(eset),las=2)

```
```{r}
mva.pairs(exprs(eset)[,1:3],log.it = FALSE,plot.method="smoothScatter")
mva.pairs(exprs(eset)[,4:6],log.it = FALSE,plot.method="smoothScatter")

```
```{r}
library(arrayQualityMetrics)
arrayQualityMetrics(eset)

```

